#line 1 "bincfg/bincfg_lex.c"

#line 3 "bincfg/bincfg_lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer bc__create_buffer
#define yy_delete_buffer bc__delete_buffer
#define yy_scan_buffer bc__scan_buffer
#define yy_scan_string bc__scan_string
#define yy_scan_bytes bc__scan_bytes
#define yy_init_buffer bc__init_buffer
#define yy_flush_buffer bc__flush_buffer
#define yy_load_buffer_state bc__load_buffer_state
#define yy_switch_to_buffer bc__switch_to_buffer
#define yypush_buffer_state bc_push_buffer_state
#define yypop_buffer_state bc_pop_buffer_state
#define yyensure_buffer_stack bc_ensure_buffer_stack
#define yy_flex_debug bc__flex_debug
#define yyin bc_in
#define yyleng bc_leng
#define yylex bc_lex
#define yylineno bc_lineno
#define yyout bc_out
#define yyrestart bc_restart
#define yytext bc_text
#define yywrap bc_wrap
#define yyalloc bc_alloc
#define yyrealloc bc_realloc
#define yyfree bc_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define bc__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer bc__create_buffer
#endif

#ifdef yy_delete_buffer
#define bc__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer bc__delete_buffer
#endif

#ifdef yy_scan_buffer
#define bc__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer bc__scan_buffer
#endif

#ifdef yy_scan_string
#define bc__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string bc__scan_string
#endif

#ifdef yy_scan_bytes
#define bc__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes bc__scan_bytes
#endif

#ifdef yy_init_buffer
#define bc__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer bc__init_buffer
#endif

#ifdef yy_flush_buffer
#define bc__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer bc__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define bc__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state bc__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define bc__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer bc__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define bc_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state bc_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define bc_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state bc_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define bc_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack bc_ensure_buffer_stack
#endif

#ifdef yylex
#define bc_lex_ALREADY_DEFINED
#else
#define yylex bc_lex
#endif

#ifdef yyrestart
#define bc_restart_ALREADY_DEFINED
#else
#define yyrestart bc_restart
#endif

#ifdef yylex_init
#define bc_lex_init_ALREADY_DEFINED
#else
#define yylex_init bc_lex_init
#endif

#ifdef yylex_init_extra
#define bc_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra bc_lex_init_extra
#endif

#ifdef yylex_destroy
#define bc_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy bc_lex_destroy
#endif

#ifdef yyget_debug
#define bc_get_debug_ALREADY_DEFINED
#else
#define yyget_debug bc_get_debug
#endif

#ifdef yyset_debug
#define bc_set_debug_ALREADY_DEFINED
#else
#define yyset_debug bc_set_debug
#endif

#ifdef yyget_extra
#define bc_get_extra_ALREADY_DEFINED
#else
#define yyget_extra bc_get_extra
#endif

#ifdef yyset_extra
#define bc_set_extra_ALREADY_DEFINED
#else
#define yyset_extra bc_set_extra
#endif

#ifdef yyget_in
#define bc_get_in_ALREADY_DEFINED
#else
#define yyget_in bc_get_in
#endif

#ifdef yyset_in
#define bc_set_in_ALREADY_DEFINED
#else
#define yyset_in bc_set_in
#endif

#ifdef yyget_out
#define bc_get_out_ALREADY_DEFINED
#else
#define yyget_out bc_get_out
#endif

#ifdef yyset_out
#define bc_set_out_ALREADY_DEFINED
#else
#define yyset_out bc_set_out
#endif

#ifdef yyget_leng
#define bc_get_leng_ALREADY_DEFINED
#else
#define yyget_leng bc_get_leng
#endif

#ifdef yyget_text
#define bc_get_text_ALREADY_DEFINED
#else
#define yyget_text bc_get_text
#endif

#ifdef yyget_lineno
#define bc_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno bc_get_lineno
#endif

#ifdef yyset_lineno
#define bc_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno bc_set_lineno
#endif

#ifdef yywrap
#define bc_wrap_ALREADY_DEFINED
#else
#define yywrap bc_wrap
#endif

#ifdef yyalloc
#define bc_alloc_ALREADY_DEFINED
#else
#define yyalloc bc_alloc
#endif

#ifdef yyrealloc
#define bc_realloc_ALREADY_DEFINED
#else
#define yyrealloc bc_realloc
#endif

#ifdef yyfree
#define bc_free_ALREADY_DEFINED
#else
#define yyfree bc_free
#endif

#ifdef yytext
#define bc_text_ALREADY_DEFINED
#else
#define yytext bc_text
#endif

#ifdef yyleng
#define bc_leng_ALREADY_DEFINED
#else
#define yyleng bc_leng
#endif

#ifdef yyin
#define bc_in_ALREADY_DEFINED
#else
#define yyin bc_in
#endif

#ifdef yyout
#define bc_out_ALREADY_DEFINED
#else
#define yyout bc_out
#endif

#ifdef yy_flex_debug
#define bc__flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug bc__flex_debug
#endif

#ifdef yylineno
#define bc_lineno_ALREADY_DEFINED
#else
#define yylineno bc_lineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define bc_wrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[266] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   50,   50,   65,   65,
       65,   65,   82,   79,   78,   75,   79,   73,   72,   68,
       74,   71,   69,   80,   80,   18,   16,   17,   19,   76,
       79,   68,   69,   76,   80,   80,   80,   28,   80,   80,
       80,   52,   50,   51,   31,   32,   33,   34,   35,   36,
       37,   38,   49,   30,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   29,   64,   65,   61,   64,   66,
       57,   56,   53,   58,   60,   66,   54,   64,   62,   53,
       58,   54,   66,   79,   78,   70,   67,   68,   69,   74,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   15,   18,   17,   76,   76,   79,    0,   77,
       79,   68,   69,    0,    0,    0,    0,    0,    0,    0,
        0,   50,   49,   64,   65,   64,    0,   63,   64,   55,
       53,   54,   60,   64,   53,   54,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       77,    0,   77,    0,   24,   25,   26,    0,   20,   21,
       22,   63,    0,   63,   64,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       77,   27,   23,   63,   59,   59,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    9,    0,    0,    0,    0,
        0,    0,    7,    0,    0,    0,    0,    0,    0,    6,
        0,    0,    0,    0,    0,    0,    0,    0,   13,    0,
        0,    0,    0,    0,    0,    0,   14,    0,    0,    3,
        0,    2,    4,   11,    5,    0,    0,   10,    8,    0,
        0,    0,    1,   12,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    1,    6,    1,    1,    1,    1,
        1,    1,    1,    7,    8,    1,    1,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   17,   18,   19,    1,
       20,    1,    1,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   38,   45,   38,
       46,   47,   48,    1,    1,    1,   49,   50,   51,   52,

       53,   27,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   38,   64,   65,   66,   67,   68,   69,   38,
       70,   38,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    2,    3,    4,    1,    5,    6,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    8,    6,
        1,    7,    7,    7,    7,    7,    7,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    8,    1,    2,    7,    7,
        7,    7,    7,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9
    } ;

static const flex_int16_t yy_base[280] =
    {   0,
        0,    0,   68,   69,  115,    0,    0,    0,   36,   39,
      534,  532,  149,  152,    0,    0,  221,    0,  291,    0,
      361,    0,  549,  431,   75, 1152,  433, 1152,   80,  472,
        0, 1152,  188, 1152,  503,    0, 1152,    0, 1152,  454,
      456,  567,  431,   76,   52,  443,   48,  512,   63,  526,
      158, 1152,  102, 1152, 1152, 1152, 1152, 1152, 1152, 1152,
     1152, 1152,    0, 1152, 1152, 1152, 1152, 1152, 1152, 1152,
     1152, 1152, 1152, 1152, 1152,    0,  105, 1152,  539,    0,
     1152, 1152,  612,    0,    0, 1152,  586,   64, 1152,  657,
     1152,  595,  165,  639,  188,  684,  637,    0,    0,    0,

      466,  442,  471,  420,  488,  594,  521,  665,  650,  467,
      607,  675, 1152,    0,    0,  694,  201,  715,  453,  721,
      729,    0,  742,  488,  581,  599,  641,  649,  644,  659,
      704,  206,    0,    0,  207,  761,  461,    0,  767,    0,
        0,  778,    0,  716,    0,    0,  717,  713,  712,  737,
      756,  462,  695,  774,  769,  771,  753,  779,  784,  780,
     1152,  462,  829,  771, 1152, 1152, 1152,  773, 1152, 1152,
     1152, 1152,  464,  836,  786,  807,  808,  804,  823,  830,
      809,  814,  822,  827,  843,  840,  848,  815,  845,  863,
      773, 1152, 1152,  811,    0, 1152,  854,  856,  855,  875,

      860,  456,  869,  879,  877,  880,  885,  889,  454,  886,
      888,  893,  896,  903,  910, 1152,  425,  911,  904,  925,
      931,  927, 1152,  923,  935,  926,  423,  936,  930, 1152,
      939,  950,  937,  957,  959,  422,  949,  964, 1152,  415,
      968,  408,  405,  387,  385,  963, 1152,  979,  171, 1152,
      169, 1152, 1152, 1152, 1152,  980,  981, 1152, 1152,  976,
      147,   63, 1152, 1152, 1152, 1036, 1045, 1052, 1061, 1070,
     1079, 1088, 1097, 1106, 1115, 1124,   91, 1133, 1142
    } ;

static const flex_int16_t yy_def[280] =
    {   0,
      265,    1,  266,  266,  265,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,  265,   17,  265,   19,
      265,   21,  265,  265,  265,  265,  267,  265,  265,  265,
      268,  265,   30,  265,  269,  270,  265,  271,  265,  272,
      273,  272,   42,  272,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  274,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  275,  265,  265,  276,  277,
      265,  265,  275,  275,  278,  265,   83,  275,  265,  265,
      265,   90,  265,  265,  265,  267,  265,   30,   33,  268,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  265,  270,  271,  272,  272,  273,  273,  265,
      273,   42,   42,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  274,  275,  265,  276,  279,  275,  276,  277,
       83,   83,  278,  275,   90,   92,  265,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      265,  273,  273,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  279,  276,  275,  265,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      273,  265,  265,  279,  275,  265,  269,  269,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  265,  269,  269,  269,  269,
      269,  269,  265,  269,  269,  269,  269,  269,  269,  265,
      269,  269,  269,  269,  269,  269,  269,  269,  265,  269,
      269,  269,  269,  269,  269,  269,  265,  269,  269,  265,
      269,  265,  265,  265,  265,  269,  269,  265,  265,  269,
      269,  269,  265,  265,    0,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265
    } ;

static const flex_int16_t yy_nxt[1223] =
    {   0,
       24,   25,   26,   25,   24,   27,   28,   29,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   24,   31,   32,
       24,   33,   33,   33,   33,   33,   33,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   35,   24,   34,   33,   33,
       33,   33,   33,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       37,   37,   45,  124,   46,   45,   95,   46,   95,   47,
      265,  265,   47,  127,  128,  144,   38,   38,   97,   97,
       97,   97,   97,   97,   97,   97,   97,  140,   45,   46,

      124,   45,   46,  132,   47,  132,  135,   47,  135,  127,
      264,  128,  144,   39,   39,   40,   25,   26,   25,   41,
       27,   28,   29,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   40,   31,   32,   40,   43,   43,   43,   43,
       43,   43,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       35,   40,   34,   43,   43,   43,   43,   43,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   49,  147,   50,   49,   95,
       50,   95,   51,  131,  263,   51,   99,   99,   99,   99,

       99,   99,   99,   99,   99,  265,  265,  132,  135,  132,
      135,   49,   50,  147,   49,   50,  259,   51,  258,  131,
       51,   52,   53,   54,   53,   52,   52,   52,   52,   55,
       56,   57,   58,   59,   60,   61,   62,   52,   52,   63,
       52,   64,   65,   66,   52,   52,   52,   52,   52,   52,
       67,   52,   52,   68,   52,   52,   69,   70,   52,   71,
       52,   72,   52,   73,   74,   52,   75,   52,   52,   65,
       66,   52,   52,   52,   52,   52,   67,   52,   52,   68,
       52,   52,   69,   70,   71,   52,   72,   52,   73,   74,
       52,   76,   77,   78,   77,   79,   80,   81,   82,   83,

       83,   83,   83,   83,   83,   83,   83,   83,   84,   85,
       86,   76,   87,   87,   87,   87,   87,   87,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   88,   76,   76,
       76,   76,   76,   76,   76,   76,   89,   76,   86,   87,
       87,   87,   87,   87,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   88,   76,   76,   76,   76,   76,   76,
       76,   86,   77,   78,   77,   86,   80,   81,   82,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   91,   85,
       86,   86,   92,   92,   92,   92,   92,   92,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   93,   86,   86,

       86,   86,   86,   86,   86,   86,   89,   86,   86,   92,
       92,   92,   92,   92,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   93,   86,   86,   86,   86,   86,   86,
       86,   94,  255,   94,  254,   94,   94,   94,   94,  123,
      123,  123,  123,  123,  123,  123,  123,  123,   94,  150,
       94,   94,  253,   94,  116,  252,  118,  161,   94,   94,
      120,  118,  250,  148,  125,  172,  191,  113,  194,  247,
      239,  116,  230,  118,  116,  150,  118,   94,  126,   94,
       98,   98,   98,   98,   98,   98,   98,   98,   98,  113,
      148,  125,  149,   99,   99,   99,   99,   99,   99,  162,

      116,  223,  121,  216,  126,  157,  181,  173,  162,  113,
      173,  151,   94,  113,  113,  164,   94,   94,  113,  149,
       99,   99,   99,   99,   99,  102,  103,  104,  105,   94,
      157,  181,   94,  106,  107,  113,  108,  109,  151,  110,
      137,  164,  111,  138,  137,  112,  153,  129,  265,   48,
      113,   48,  102,  103,  104,  105,  265,  137,   94,  106,
      107,  130,  108,  109,  265,  110,  265,  111,  113,  265,
      112,  265,  265,  153,  129,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  137,  139,  137,  130,  123,  123,
      123,  123,  123,  123,  142,  142,  142,  142,  142,  142,

      142,  142,  142,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  265,  265,  165,  123,  123,  123,  123,  123,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  152,
      158,  265,  166,  142,  142,  142,  142,  142,  142,   94,
      165,  113,  265,   94,   94,   97,   97,   97,   97,   97,
       97,   97,   97,   97,  113,  152,   94,  158,  166,   94,
      142,  142,  142,  142,  142,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  167,  265,  168,  169,  146,  146,
      146,  146,  146,  146,  265,   94,  154,  265,  265,  265,
      155,  156,  170,  265,  116,  265,  159,  113,   94,   94,

      167,  265,  168,  169,  265,  146,  146,  146,  146,  146,
      160,  116,  113,  154,  116,  118,  156,  155,  170,  120,
      118,   94,  113,  159,  265,   94,   94,  265,  265,  118,
      265,  265,  118,  163,  118,  118,  160,  171,   94,  182,
      116,   94,  113,  175,  176,  265,  118,  177,  178,  118,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  113,
      113,  121,  137,  171,  182,  138,  137,   94,  137,  175,
      176,  174,  137,  177,  178,  121,  179,  161,  187,  137,
      265,  265,  265,  265,  113,  137,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  180,  192,  183,  193,  265,

      113,  179,  185,  113,  186,  187,  137,  139,  137,  190,
      184,  195,  137,  139,  137,  172,  113,  188,  113,  162,
      180,  113,  189,  192,  183,  193,  113,  113,  185,  118,
      186,  113,  196,  120,  118,  190,  184,  137,  195,  197,
      138,  137,  188,  198,  199,  265,  118,  189,  201,  118,
      208,  113,  200,  202,  137,  113,  113,  173,  265,  196,
      203,  113,  113,  204,  205,  197,  265,  265,  198,  113,
      113,  199,  206,  201,  113,  121,  208,  113,  202,  200,
      207,  137,  139,  137,  209,  203,  210,  113,  212,  204,
      113,  205,  113,  211,  213,  113,  214,  265,  206,  265,

      215,  113,  113,  113,  217,  265,  207,  113,  218,  209,
      113,  224,  265,  210,  212,  220,  113,  219,  211,  213,
      221,  222,  113,  214,  113,  215,  113,  113,  226,  227,
      217,  225,  113,  113,  218,  113,  113,  228,  224,  229,
      113,  220,  219,  113,  232,  231,  221,  222,  233,  238,
      113,  113,  234,  241,  226,  227,  225,  113,  113,  235,
      265,  265,  236,  228,  237,  229,  242,  240,  244,  232,
      113,  231,  113,  113,  113,  233,  238,  113,  113,  234,
      241,  245,  113,  113,  113,  235,  113,  236,  243,  248,
      237,  246,  242,  240,  244,  249,  113,  113,  256,  251,

      265,  265,  257,  260,  113,  265,  113,  262,  245,  261,
      113,  113,  265,  243,  248,  113,  265,  246,  265,  265,
      265,  249,  265,  113,  256,  251,  113,  113,  113,  257,
      260,  265,  265,  262,  265,  261,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   96,  265,  265,  265,   96,
      265,   96,  100,  100,  265,  100,  100,  100,  100,  100,
      100,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      114,  114,  265,  114,  114,  114,  114,  265,  114,  115,
      115,  265,  115,  115,  115,  115,  115,  115,  117,  265,
      265,  265,  117,  265,  117,  265,  117,  119,  119,  265,

      265,  119,  119,  119,  119,  119,  133,  133,  265,  133,
      133,  133,  133,  133,  133,  134,  265,  265,  265,  265,
      134,  134,  265,  134,  136,  136,  265,  265,  136,  136,
      136,  136,  136,  143,  143,  265,  143,  143,  143,  143,
      143,  143,  137,  137,  265,  265,  137,  137,  137,  137,
      137,   23,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265
    } ;

static const flex_int16_t yy_chk[1223] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    9,   45,    9,   10,   25,   10,   25,    9,
       44,   44,   10,   47,   49,   88,    3,    4,   29,   29,
       29,   29,   29,   29,   29,   29,   29,  277,    9,    9,

       45,   10,   10,   53,    9,   53,   77,   10,   77,   47,
      262,   49,   88,    3,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,   13,   93,   13,   14,   95,
       14,   95,   13,   51,  261,   14,   33,   33,   33,   33,

       33,   33,   33,   33,   33,  117,  117,  132,  135,  132,
      135,   13,   13,   93,   14,   14,  251,   13,  249,   51,
       14,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   19,   19,   19,   19,   19,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,

       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   24,  245,   27,  244,   24,   24,   27,   27,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   24,  104,
       27,   24,  243,   27,   40,  242,   41,  119,   40,   40,
       41,   41,  240,  102,   46,  137,  162,  104,  173,  236,
      227,   40,  217,   41,   40,  104,   41,   24,   46,   27,
       30,   30,   30,   30,   30,   30,   30,   30,   30,  102,
      102,   46,  103,   30,   30,   30,   30,   30,   30,  119,

       40,  209,   41,  202,   46,  110,  152,  137,  162,  152,
      173,  105,   48,  101,  110,  124,   48,   48,  103,  103,
       30,   30,   30,   30,   30,   35,   35,   35,   35,   48,
      110,  152,   48,   35,   35,  105,   35,   35,  105,   35,
       79,  124,   35,   79,   79,   35,  107,   50,   23,   12,
       35,   11,   35,   35,   35,   35,    0,   79,   48,   35,
       35,   50,   35,   35,    0,   35,    0,   35,  107,    0,
       35,   42,   42,  107,   50,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   79,   79,   79,   50,   42,   42,
       42,   42,   42,   42,   87,   87,   87,   87,   87,   87,

       87,   87,   87,   92,   92,   92,   92,   92,   92,   92,
       92,   92,    0,    0,  125,   42,   42,   42,   42,   42,
       83,   83,   83,   83,   83,   83,   83,   83,   83,  106,
      111,    0,  126,   83,   83,   83,   83,   83,   83,   94,
      125,  106,    0,   94,   94,   97,   97,   97,   97,   97,
       97,   97,   97,   97,  111,  106,   94,  111,  126,   94,
       83,   83,   83,   83,   83,   90,   90,   90,   90,   90,
       90,   90,   90,   90,  127,    0,  128,  129,   90,   90,
       90,   90,   90,   90,   96,   94,  108,    0,   96,   96,
      108,  109,  130,    0,  116,    0,  112,  109,  116,  116,

      127,   96,  128,  129,   96,   90,   90,   90,   90,   90,
      112,  116,  108,  108,  116,  118,  109,  108,  130,  118,
      118,  120,  112,  112,    0,  120,  120,    0,    0,  121,
       96,    0,  118,  121,  121,  118,  112,  131,  120,  153,
      116,  120,  153,  144,  147,    0,  121,  148,  149,  121,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  149,
      148,  118,  136,  131,  153,  136,  136,  120,  139,  144,
      147,  139,  139,  148,  149,  121,  150,  191,  157,  136,
        0,    0,    0,    0,  150,  139,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  151,  164,  154,  168,    0,

      157,  150,  155,  151,  156,  157,  136,  136,  136,  160,
      154,  175,  139,  139,  139,  194,  155,  158,  156,  191,
      151,  154,  159,  164,  154,  168,  158,  160,  155,  163,
      156,  159,  176,  163,  163,  160,  154,  174,  175,  177,
      174,  174,  158,  178,  179,    0,  163,  159,  181,  163,
      188,  178,  180,  182,  174,  177,  181,  194,    0,  176,
      183,  182,  188,  184,  185,  177,    0,    0,  178,  183,
      179,  179,  186,  181,  184,  163,  188,  180,  182,  180,
      187,  174,  174,  174,  189,  183,  190,  186,  198,  184,
      185,  185,  189,  197,  199,  187,  200,    0,  186,    0,

      201,  197,  199,  198,  203,    0,  187,  201,  204,  189,
      190,  210,    0,  190,  198,  206,  203,  205,  197,  199,
      207,  208,  200,  200,  205,  201,  204,  206,  212,  213,
      203,  211,  207,  210,  204,  211,  208,  214,  210,  215,
      212,  206,  205,  213,  219,  218,  207,  208,  220,  226,
      214,  219,  221,  229,  212,  213,  211,  215,  218,  222,
        0,    0,  224,  214,  225,  215,  231,  228,  233,  219,
      224,  218,  220,  226,  222,  220,  226,  229,  221,  221,
      229,  234,  225,  228,  233,  222,  231,  224,  232,  237,
      225,  235,  231,  228,  233,  238,  237,  232,  246,  241,

        0,    0,  248,  256,  234,    0,  235,  260,  234,  257,
      246,  238,    0,  232,  237,  241,    0,  235,    0,    0,
        0,  238,    0,  260,  246,  241,  248,  256,  257,  248,
      256,    0,    0,  260,    0,  257,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  267,    0,    0,    0,  267,
        0,  267,  268,  268,    0,  268,  268,  268,  268,  268,
      268,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      270,  270,    0,  270,  270,  270,  270,    0,  270,  271,
      271,    0,  271,  271,  271,  271,  271,  271,  272,    0,
        0,    0,  272,    0,  272,    0,  272,  273,  273,    0,

        0,  273,  273,  273,  273,  273,  274,  274,    0,  274,
      274,  274,  274,  274,  274,  275,    0,    0,    0,    0,
      275,  275,    0,  275,  276,  276,    0,    0,  276,  276,
      276,  276,  276,  278,  278,    0,  278,  278,  278,  278,
      278,  278,  279,  279,    0,    0,  279,  279,  279,  279,
      279,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "bincfg/bincfg_lex_real.l"
/* Scanner for INTVPC .CFG files */
#define YY_NO_INPUT 1










#line 24 "bincfg/bincfg_lex_real.l"
/* Clang doesn't like the unreachable code in Flex's generated output. */
#ifdef __clang__
#pragma clang diagnostic ignored "-Wunreachable-code"
#endif

/* put any #includes here */
#include "config.h"
#include "lzoe/lzoe.h"
#include "bincfg/bincfg.h"
#include "bincfg/bincfg_grmr.tab.h"
#include "misc/types.h"

extern int      bc_lex(void);
int             bc_line_no = 1;
int             bc_dec; 
uint32_t         bc_hex;
char           *bc_txt = NULL;
static unsigned bc_txt_alloc = 0;

typedef enum nlsm_t 
{
    NLSM_START = 0,
    NLSM_SAWCR,
    NLSM_SAWEOF,
    NLSM_SAWEOF2,
    NLSM_DIDEOF
} nlsm_t;

static nlsm_t nlsm_state = NLSM_START;

/* Simple character-at-a-time state machine for reading input.  It serves
   three purposes:  

   1.  Convert Mac and Windows style NL to UNIX style.
   2.  Insert an extra NL at EOF to ensure the last line is NL terminated
   3.  Reads from an LZFILE* instead of a FILE*.
*/
static int nlsm_next_char(void)
{
    int next_char = EOF;

again: 
    if (nlsm_state == NLSM_SAWEOF)
    {
        nlsm_state = NLSM_SAWEOF2;
        return 10;
    }
    if (nlsm_state == NLSM_SAWEOF2)
    {
        nlsm_state = NLSM_DIDEOF;
        return EOF;
    }

    next_char = lzoe_fgetc( (LZFILE *)bc_in );

    if (nlsm_state == NLSM_DIDEOF)
    {
        if (next_char != EOF)
            nlsm_state = NLSM_START;
        else
            return EOF;
    }

    if (next_char == EOF)
    {
        nlsm_state = NLSM_SAWEOF;
        return 10; /* extra CR at EOF */
    }

    if (next_char == 13)
    {
        nlsm_state = NLSM_SAWCR;
        return 10;
    }

    if (next_char == 10 && nlsm_state == NLSM_SAWCR)
    {
        nlsm_state = NLSM_START;
        goto again; /* eat LF after CR, since we converted CR to LF */
    }

    nlsm_state = NLSM_START;
    return next_char;
}


#define YYTEXT_TO_BC_TXT(unquote) \
        do {                                                            \
            size_t uyyleng = yyleng > 0 ? yyleng : 0;                   \
            if (uyyleng >= bc_txt_alloc)                                \
            {                                                           \
                if (!bc_txt_alloc)                                      \
                    bc_txt_alloc = 256;                                 \
                                                                        \
                while (bc_txt_alloc <= uyyleng)                         \
                    bc_txt_alloc <<= 1;                                 \
                                                                        \
                bc_txt = (char *)realloc(bc_txt, bc_txt_alloc);         \
                                                                        \
                if (!bc_txt)                                            \
                    return TOK_ERROR_OOM;                               \
            }                                                           \
                                                                        \
            if (!unquote || uyyleng < 2)                                \
                strcpy(bc_txt, yytext);                                 \
            else                                                        \
                strcpy(bc_txt, cfg_unquote_str(yytext));                \
        } while (0)

#define YY_INPUT(buf,result,max_size)                                   \
        do {                                                            \
            int c_;                                                     \
            unsigned i_;                                                \
            unsigned ms = max_size > 0 ? max_size : 0;                  \
                                                                        \
            i_ = 0;                                                     \
            while (i_ < ms && (c_ = nlsm_next_char()) != EOF)           \
                buf[i_++] = c_;                                         \
                                                                        \
            result = i_ > 0 ? i_ : YY_NULL;                             \
                                                                        \
        } while (0);                                                    \


#line 1200 "bincfg/bincfg_lex.c"
#line 1201 "bincfg/bincfg_lex.c"

#define INITIAL 0
#define SEC_IGN 1
#define SEC_VAR 2
#define SEC_BSW 3
#define SEC_MAP 4
#define SEC_EBK 5
#define SEC_ATR 6
#define SEC_PRL 7
#define SEC_MC0 8
#define SEC_MC1 9
#define SEC_MC2 10

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 153 "bincfg/bincfg_lex_real.l"

#line 155 "bincfg/bincfg_lex_real.l"
                   
 
/* -------------------------------------------------------------------- */
/*  Rules for identifying section headers.                              */
/* -------------------------------------------------------------------- */
 
#line 1435 "bincfg/bincfg_lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 266 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 265 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 161 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_BSW); return  TOK_SEC_BANKSWITCH;     }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 162 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MAP); return  TOK_SEC_MAPPING;        }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 163 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_EBK); return  TOK_SEC_ECSBANK;        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 164 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_ATR); return  TOK_SEC_MEMATTR;        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 165 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_PRL); return  TOK_SEC_PRELOAD;        }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 167 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC0); return  TOK_SEC_MACRO;          }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 169 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_VAR); return  TOK_SEC_VARS;           }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 170 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_VAR); return  TOK_SEC_JOYSTICK;       }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 171 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_VAR); return  TOK_SEC_KEYS;           }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 172 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_VAR); return  TOK_SEC_CAPSLOCK;       }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 173 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_VAR); return  TOK_SEC_NUMLOCK;        }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 174 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_VAR); return  TOK_SEC_SCROLLLOCK;     }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 176 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_IGN); return  TOK_SEC_DISASM;         }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 177 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_IGN); return  TOK_SEC_VOICES;         }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 179 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_IGN); return  TOK_SEC_UNKNOWN;        }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Mini-scanner for ignored sections:  Just eat them right up.         */
/* -------------------------------------------------------------------- */

case YY_STATE_EOF(SEC_IGN):
#line 186 "bincfg/bincfg_lex_real.l"
{   BEGIN(INITIAL); return '\n';                    }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 187 "bincfg/bincfg_lex_real.l"
{   bc_line_no++; /* eat newlines */                }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 188 "bincfg/bincfg_lex_real.l"
{   /* eat comments */                              }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 189 "bincfg/bincfg_lex_real.l"
{   /* eat non-section openers. */                  }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 190 "bincfg/bincfg_lex_real.l"
{   yyless(0);  BEGIN(INITIAL); return '\n';        }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Keywords that are only valid in memory-attribute section.           */
/* -------------------------------------------------------------------- */

case 20:
YY_RULE_SETUP
#line 197 "bincfg/bincfg_lex_real.l"
{   return TOK_RAM;                                 }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 198 "bincfg/bincfg_lex_real.l"
{   return TOK_ROM;                                 }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 199 "bincfg/bincfg_lex_real.l"
{   return TOK_WOM;                                 }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 200 "bincfg/bincfg_lex_real.l"
{   return TOK_PAGE;                                }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Keywords that are only valid in the mapping section.                */
/* -------------------------------------------------------------------- */

case 24:
YY_RULE_SETUP
#line 207 "bincfg/bincfg_lex_real.l"
{   return TOK_RAM;                                 }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 208 "bincfg/bincfg_lex_real.l"
{   return TOK_ROM;                                 }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 209 "bincfg/bincfg_lex_real.l"
{   return TOK_WOM;                                 }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 210 "bincfg/bincfg_lex_real.l"
{   return TOK_PAGE;                                }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Keywords that are only valid in the ecsbank section.                */
/* -------------------------------------------------------------------- */

case 28:
YY_RULE_SETUP
#line 217 "bincfg/bincfg_lex_real.l"
{   return ':';                                     }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Keywords that are only valid in the macro section.                  */
/* -------------------------------------------------------------------- */

case 29:
YY_RULE_SETUP
#line 224 "bincfg/bincfg_lex_real.l"
{   yyless(0); BEGIN(INITIAL);   /*]*/              }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 225 "bincfg/bincfg_lex_real.l"
{   return TOK_MAC_QUIET;                           }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 226 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); bc_hex=0; return TOK_MAC_REG;   }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 227 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); bc_hex=1; return TOK_MAC_REG;   }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 228 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); bc_hex=2; return TOK_MAC_REG;   }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 229 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC1); bc_hex=3; return TOK_MAC_REG;   }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 230 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); bc_hex=4; return TOK_MAC_REG;   }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 231 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); bc_hex=5; return TOK_MAC_REG;   }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 232 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); bc_hex=6; return TOK_MAC_REG;   }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 233 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); bc_hex=7; return TOK_MAC_REG;   }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 234 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); return TOK_MAC_AHEAD;           }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 235 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); return TOK_MAC_BLANK;           }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 236 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); return TOK_MAC_INSPECT;         }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 237 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC1); return TOK_MAC_LOAD;            }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 238 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); return TOK_MAC_RUNTO;           }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 239 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); return TOK_MAC_POKE;            }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 240 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); return TOK_MAC_RUN;             }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 241 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); return TOK_MAC_TRACE;           }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 242 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); return TOK_MAC_VIEW;            }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 243 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC1); return TOK_MAC_WATCH;           }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 244 "bincfg/bincfg_lex_real.l"
{   /* ignore comments.       */                    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 245 "bincfg/bincfg_lex_real.l"
{   /* ignore whitespace.     */                    }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 246 "bincfg/bincfg_lex_real.l"
{   bc_line_no++; return '\n';                      }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 247 "bincfg/bincfg_lex_real.l"
{   /* ignore unknown lines.  */                    }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Special secondary, tertiary states for macro processing.  Grrr...   */
/*  We enter this state after parsing the first 'name' on a line.       */
/*  This keeps hex ranges that aren't $ adorned from turning into       */
/*  TOK_NAMEs.  Too much of the grammar comes into the lexer.  :-P      */
/* -------------------------------------------------------------------- */

case 53:
YY_RULE_SETUP
#line 258 "bincfg/bincfg_lex_real.l"
{   
                                    BEGIN(SEC_MC2);
                                    bc_dec = atoi(yytext);
                                    sscanf(yytext    , "%x", &bc_hex); 
                                    YYTEXT_TO_BC_TXT(0);
                                    return  TOK_DEC;    
                                }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 265 "bincfg/bincfg_lex_real.l"
{   
                                    BEGIN(SEC_MC2);
                                    bc_dec = atoi(yytext);
                                    sscanf(yytext    , "%x", &bc_hex); 
                                    YYTEXT_TO_BC_TXT(0);
                                    return  TOK_HEX;    
                                }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 272 "bincfg/bincfg_lex_real.l"
{   
                                    BEGIN(SEC_MC2);
                                    bc_dec = atoi(yytext + 1);
                                    sscanf(yytext + 1, "%x", &bc_hex); 
                                    YYTEXT_TO_BC_TXT(0);
                                    return  TOK_HEX;    
                                }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 279 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); return '-';                 }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 280 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); return ',';                 }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 281 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); return ':';                 }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 282 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); return TOK_PAGE;            }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 283 "bincfg/bincfg_lex_real.l"
{   BEGIN(SEC_MC2); /* eat comments.  */        }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 284 "bincfg/bincfg_lex_real.l"
{   bc_line_no++; BEGIN(SEC_MC0); return '\n';  }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 285 "bincfg/bincfg_lex_real.l"
{   yyless(0); BEGIN(INITIAL);   /*]*/          }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 287 "bincfg/bincfg_lex_real.l"
{
                                    BEGIN(SEC_MC2);
                                    YYTEXT_TO_BC_TXT(1);
                                    return TOK_STRING;
                                }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 293 "bincfg/bincfg_lex_real.l"
{   
                                    BEGIN(SEC_MC2);
                                    YYTEXT_TO_BC_TXT(0);                
                                    return  TOK_NAME;   
                                }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 299 "bincfg/bincfg_lex_real.l"
{ /* ignore whitespace. */                    }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 300 "bincfg/bincfg_lex_real.l"
{ YYTEXT_TO_BC_TXT(0); return TOK_ERROR_BAD;  }
	YY_BREAK
 
/* -------------------------------------------------------------------- */
/*  Main scanner with common rules across most sections.                */
/* -------------------------------------------------------------------- */

case 67:
YY_RULE_SETUP
#line 307 "bincfg/bincfg_lex_real.l"
{   
                bc_dec = atoi(yytext);
                sscanf(yytext + 1, "%x", &bc_hex); 
                YYTEXT_TO_BC_TXT(0);
                return  TOK_DECONLY;    
            }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 313 "bincfg/bincfg_lex_real.l"
{   
                bc_dec = atoi(yytext);
                sscanf(yytext    , "%x", &bc_hex); 
                YYTEXT_TO_BC_TXT(0);
                return  TOK_DEC;    
            }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 319 "bincfg/bincfg_lex_real.l"
{   
                bc_dec = atoi(yytext);
                sscanf(yytext    , "%x", &bc_hex); 
                YYTEXT_TO_BC_TXT(0);
                return  TOK_HEX;    
            }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 325 "bincfg/bincfg_lex_real.l"
{   
                bc_dec = atoi(yytext + 1);
                sscanf(yytext + 1, "%x", &bc_hex); 
                YYTEXT_TO_BC_TXT(0);
                return  TOK_HEX;    
            }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 331 "bincfg/bincfg_lex_real.l"
{   return '=';                                             }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 332 "bincfg/bincfg_lex_real.l"
{   return '-';                                             }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 333 "bincfg/bincfg_lex_real.l"
{   return ',';                                             }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 334 "bincfg/bincfg_lex_real.l"
{   /* eat comments.  */                                    }
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 335 "bincfg/bincfg_lex_real.l"
{   bc_line_no++;
                if (YY_START == SEC_MC1) BEGIN(SEC_MC0);
                return '\n';        /* comments and newlines are same */
            }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 340 "bincfg/bincfg_lex_real.l"
{   
                YYTEXT_TO_BC_TXT(0);                
                return TOK_NAME;   
            }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 345 "bincfg/bincfg_lex_real.l"
{
                YYTEXT_TO_BC_TXT(1);
                return TOK_STRING;
            }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 350 "bincfg/bincfg_lex_real.l"
{   /* eat whitespace */                                    }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 351 "bincfg/bincfg_lex_real.l"
{ 
    YYTEXT_TO_BC_TXT(0); 
#ifdef DEBUG
    fprintf(stderr, "BAD2: %d\n", yytext[0]);
#endif
    return TOK_ERROR_BAD;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 358 "bincfg/bincfg_lex_real.l"
{
    YYTEXT_TO_BC_TXT(0); 
#ifdef DEBUG
    fprintf(stderr, "BAD3: %d\n", yytext[0]);
#endif
    return TOK_ERROR_BAD;  
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 366 "bincfg/bincfg_lex_real.l"
ECHO;
	YY_BREAK
#line 2007 "bincfg/bincfg_lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SEC_VAR):
case YY_STATE_EOF(SEC_BSW):
case YY_STATE_EOF(SEC_MAP):
case YY_STATE_EOF(SEC_EBK):
case YY_STATE_EOF(SEC_ATR):
case YY_STATE_EOF(SEC_PRL):
case YY_STATE_EOF(SEC_MC0):
case YY_STATE_EOF(SEC_MC1):
case YY_STATE_EOF(SEC_MC2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 266 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 266 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 265);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 366 "bincfg/bincfg_lex_real.l"


/* ======================================================================== */
/*  This program is free software; you can redistribute it and/or modify    */
/*  it under the terms of the GNU General Public License as published by    */
/*  the Free Software Foundation; either version 2 of the License, or       */
/*  (at your option) any later version.                                     */
/*                                                                          */
/*  This program is distributed in the hope that it will be useful,         */
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of          */
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU       */
/*  General Public License for more details.                                */
/*                                                                          */
/*  You should have received a copy of the GNU General Public License along */
/*  with this program; if not, write to the Free Software Foundation, Inc., */
/*  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.             */
/* ======================================================================== */
/*                 Copyright (c) 2003-+Inf, Joseph Zbiciak                  */
/* ======================================================================== */

